### ISSUE TITLE
Better docs?  For scan reults?

### ISSUE THREAD

**Issue by jpatrick-ztel** [githubrlloyd/veracode-pipeline#1]
Hopefully this isn't a is mostly a nit-pick, feel free to close.

I've noticed that the docs for this, aren't really super-up-to-date with the action (But many thanks for updating the action!)

One thing I run into, is running the action as part of a Github workflow, and really trying to pull out results, and various things, without needing to  to write a small app to do it..

Example, we'd like to send results to slack, on the status of the results (aka `'Results Ready`  versus `Incomplete` etc..)

Currently we sort of run it like this:

```
java -jar vcli.jar -vid 12345ShortIDdHere -vkey 12345longerkeyhere -action getbuildinfo -appid=111111 > results.tmp
```

which would net us results in xml into a tmp file..  which I try to quickly chop up using bash-y stuff, versus doing a full read of the xml data:

(values changed from my real ones, obviously)

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<buildinfo xmlns="https://analysiscenter.veracode.com/schema/4.0/buildinfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" account_id="00000" ap
p_id="00000" build_id="0000000" buildinfo_version="1.4" xsi:schemaLocation="https://analysiscenter.veracode.com/schema/4.0/buildinfo https://analysisc
enter.veracode.com/resource/4.0/buildinfo.xsd">
  <build build_id="00000" grace_period_expired="false" legacy_scan_engine="false" lifecycle_stage="Not Specified" platform="Not Specified" policy_com
pliance_status="Pass" policy_name="Veracodexxxxx" policy_updated_date="2020-10-09T13:46:11-04:00" policy_version="1" results_ready="true" r
ules_status="Pass" scan_overdue="false" submitter=" User Name" version="xxxxyyyyxxxxyyyyzzzz">
    <analysis_unit analysis_type="Static" engine_version="datefield here" published_date="2020-10-09T13:45:34-04:00" published_date_sec="datsec info hee" st
atus="Results Ready"/>
  </build>
</buildinfo>
```

And all that I really need is the `Results Ready` field (or whatever other value would show up there, which would spur another action based on it's value..etc)

Is there a faster way, aside from grabbing the whole XML file, and chunking it via bash or (insert language that runs on ubuntu here) to grab the results status?

Thanks for updating the app, and maintaining it, it's truly appreciated.

**Comment by githubrlloyd** [comment]
Hi - thanks for the feedback and taking a look at the Veracode actions. This particular action you posted about was a work-in-progress that ended up not being needed. I'll close out this Repo given that situation. But we do have two Veracode GitHub Actions that are more complete and may be worth reviewing:

Veracode Upload and Scan - https://github.com/veracode/veracode-uploadandscan-action
Veracode Static Analysis Pipeline Scan https://github.com/veracode/veracode-pipeline-scan-results-to-sarif

The Upload and Scan most closely mirrors the Java Wrapper API that you have been using. Though the action focuses more on initiating the Upload and Scan and less about parsing the output results. The Pipeline scan is a different action which uses our Veracode Pipeline Scan services and returns a raw results.json file which can be imported to GitHub using the SARIF output.

Feel free to post any issues or feedback on the relevant GitHub repo's for those actions. 

Slack integration - another example (not a GitHub action) that you might find useful - https://github.com/ctcampbell/veracode-slack-slash-command
